### ISSUE TITLE
Playback speed didn't preserve after skip ads

### ISSUE THREAD

**Issue by Artin0123** [ion1/userscripts#2]
Change video speed to 2x until encounter ads (black screen blinks).
Speed reset to 1x.

**Comment by ion1** [comment]
Thanks for the report! I believe I found the issue and fixed it in version 0.0.28.

If you still encounter it, feel free to reopen the issue. In that case, please try to replicate it with a version of the userscript with debug output which I just added: https://ion1.github.io/userscripts/youtube-mute-skip-ads.debug.user.js

I don't recommend using that version when not hunting a bug though, it adds a lot into the developer console.
